### ISSUE TITLE
Possible bug in SocketedStreamingSolver.inl

### ISSUE THREAD

**Issue by science-enthusiast** [mkazhdan/DMG#2]
In line 335, OffsetX is not invoked as a function call:

void SocketedStreamingSolver< Channels , SyncType >::Set( int rSize ){ Set( -OffsetX , 0 , 0 , 0 , 0 , rSize ); }

This error shows up while building the project by running make.

**Comment by mkazhdan** [comment]
Thanks for calling that to our attention.
An updated version of the code has been posted.
Please let me know if the new code resolves the issue.
(I'm assuming you were compiling under clang.)

**Comment by science-enthusiast** [comment]
Thanks for your reply. I tried with the updated code. I again get the same error.

The error is happening because of these lines of code in LaplacianMatrix/SocketedStreamingSolver.inl:

template< int Channels , class SyncType >
void SocketedStreamingSolver< Channels , SyncType >::Set( int rSize ){ Set( -OffsetX , 0 , 0 , 0 , 0 , rSize ); }

It is happening because of the expression -Offset. The error is "error: wrong type argument to unary minus".

I am using gcc.

Note: I could get the project to build by commenting out the above two lines and by adding -lboost_chrono in LFLAGS in order to deal with the following error which shows up later:

/usr/bin/ld: ./Util/BaseMultiStreamIO.o: in function `void boost::this_thread::sleep_for<long, boost::ratio<1l, 1000l> >(boost::chrono::duration<long, boost::ratio<1l, 1000l> > const&)':
BaseMultiStreamIO.cpp:(.text._ZN5boost11this_thread9sleep_forIlNS_5ratioILl1ELl1000EEEEEvRKNS_6chrono8durationIT_T0_EE[_ZN5boost11this_thread9sleep_forIlNS_5ratioILl1ELl1000EEEEEvRKNS_6chrono8durationIT_T0_EE]+0x6a): undefined reference to `boost::chrono::steady_clock::now()'

**Comment by mkazhdan** [comment]
Sorry. I updated the github repo but forgot to update the link to the .zip file.
It should be fixed now.

**Comment by science-enthusiast** [comment]
Thank you very much for the clarification.

Yes, I now see the code fix using the macro NEW_CODE.

At my end, I still need to take care of the following error by adding -lboost_chrono in LFLAGS:

/usr/bin/ld: ./Util/BaseMultiStreamIO.o: in function void boost::this_thread::sleep_for<long, boost::ratio<1l, 1000l> >(boost::chrono::duration<long, boost::ratio<1l, 1000l> > const&)': BaseMultiStreamIO.cpp:(.text._ZN5boost11this_thread9sleep_forIlNS_5ratioILl1ELl1000EEEEEvRKNS_6chrono8durationIT_T0_EE[_ZN5boost11this_thread9sleep_forIlNS_5ratioILl1ELl1000EEEEEvRKNS_6chrono8durationIT_T0_EE]+0x6a): undefined reference to boost::chrono::steady_clock::now()'

**Comment by mkazhdan** [comment]
What version of boost are you using?

**Comment by science-enthusiast** [comment]
Thank you for your reply.

My boost version is 1.75.0. The Readme mentions that the project has been developed and tested with version 1.55.0.

**Comment by mkazhdan** [comment]
Got it. But with the added flags everything compiles?

**Comment by science-enthusiast** [comment]
Running make results in the following:

mkdir -p Bin/
g++ -o Bin/Client ./Util/BaseMultiStreamIO.o ./Util/CmdLineParser.o ./Util/GridStream.o ./Util/Half/half.o ./Util/MultiStreamIO.o ./Util/Socket.o ./Util/Time.o ./Util/XPlatform.o ./ClientSocket/ClientSocket.o -lgomp -lz -lpng -ltiff -ljpeg -lboost_thread -lboost_system -lboost_chrono -lpthread -O3 
/usr/bin/ld: ./Util/GridStream.o: in function `FileBackedGrid::FileBackedGrid(int, int)':
GridStream.cpp:(.text+0xea3): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
mkdir -p Bin/
g++ -o Bin/Server ./Util/BaseMultiStreamIO.o ./Util/CmdLineParser.o ./Util/GridStream.o ./Util/Half/half.o ./Util/MultiStreamIO.o ./Util/Socket.o ./Util/Time.o ./Util/XPlatform.o ./ServerSocket/ServerSocket.o -lgomp -lz -lpng -ltiff -ljpeg -lboost_thread -lboost_system -lboost_chrono -lpthread -O3 
/usr/bin/ld: ./Util/GridStream.o: in function `FileBackedGrid::FileBackedGrid(int, int)':
GridStream.cpp:(.text+0xea3): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'

The build is successful except for some warnings.

I am trying to run a server with one client, using the Jaffa data available in the Poisson reconstruction project. The server is launching successfully, I think. I get a memory error with the client. I will reduce the size of the inputs and try.

Thanks for sharing these projects.

**Comment by mkazhdan** [comment]
Can you share the commands you are using for the client and the server?
Also, because I could not get openmp to work with the (older) version of clang on my computer, the Makefile implementation for clang may not support parallelism.

**Comment by science-enthusiast** [comment]
I have been using gcc.

I am using 1 client only. That is because I am using the pixels.png and labels.png files from the Jaffa dataset given in the Poisson reconstruction project. I have not yet split them into two parts, in order to launch 2 clients.

Server command:

./Server --count 1

Which outputs:

Server Address: 127.0.1.1:42157

Client command:

./Client --pixels ../../PoissonRecon/Data/Jaffa/pixels.png --labels ../../PoissonRecon/Data/Jaffa/labels.png --out out.jpeg --address 127.0.1.1 --port 42157 --threads 1 --index 0 --inCore

Which results in:

Connecting to server...
Failed to allocate memory backed grid of size 285528 x 9492

**Comment by mkazhdan** [comment]
In principal, you can run a single client in multi-threaded mode. (E.g. by specifying "--threads 2".)
What happens if you leave off the "--inCore" flag when running the client?

**Comment by science-enthusiast** [comment]
Yes, I could get the expected stitched output when "--inCore" was left out. Sorry, I should have looked more carefully at the documentation.
Thank you for your time.
Sometime soon, I will try setting number of threads > 1.
Update: The code works with "--threads 2" and the speed-up is observable.
